### ISSUE TITLE
Updates to readme and resources

### ISSUE THREAD

**Issue by whoabuddy** [blockstackers/contribute-blockstack#7]
Looking over the readme, there are a few things that could be updated, please see my notes below!

**Tasks**

- [ ] add a note for testnet under engineering resources
- [ ] update PoX meets every Friday, and has folded into the testnet ambassador program
- [ ] update PoX [pm repo](https://github.com/blockstackers/pox_pm) has more info than here (or point there instead?)
- [ ] add proposals repository to resources, reorganize resources together
- [ ] update governance proposal timeline, possibly simplify?

**Questions**

Would it make more sense to provide a brief description of each working group, then redirect a link to their respective repositories?

This would make it so there is only one reference to resource materials, and prevent things from getting out of date (or out of sync) like the content between this readme and the [PoX pm readme](https://github.com/blockstackers/pox_pm).

Are there still monthly engineering meetings, and will the resume?

All links to the community calendar produce `No events found.` - what is the best way to keep these updated or "evergreen"?
